Interface-Certificadora/sisnato_backend2

src/api/file/file.controller.ts, src/api/solicitacao/solicitacao.service.ts, src/api/user/user.controller.ts
=> [#101] erro e impressão de pré imagem

src/api/chamado/chamado.service.ts, src/api/solicitacao/solicitacao.service.ts, src/sequelize/providers/fcweb.ts
[#146] correção rota /chamado
https://jira.arinterface.com.br/work_packages/146
=> 🐛 :fix correção rota /chamado DYNAMIC_SERVER_USAGE backend

.vscode/settings.json, src/api/now/now.service.ts, src/api/pix/pix.service.ts, src/api/relatorio_financeiro/relatorio_financeiro.service.ts, src/api/solicitacao/solicitacao.service.ts
- Adiciona clientes Prisma distintos para leitura () e escrita ()
- Refatora serviços para usar os clientes Prisma apropriados para cada operação
- Remove  e  desnecessários do Prisma
=> ♻️ refactor: Separa operações de leitura e escrita do Prisma

src/api/direto/direto.controller.ts, src/api/direto/direto.service.ts, src/api/solicitacao/solicitacao.service.ts, src/prisma/decorators/database-resilient.decorator.ts, src/prisma/prisma.service.ts
- Refatora o tratamento de erros e a resiliência das operações do banco de dados.
- Implementa um decorator  para operações de banco de dados com lógica de retry.
- Adiciona o método  no  para lidar com erros transientes.
- Ajusta o tratamento de logs e mensagens de erro.
=> ♻️ refactor: Melhora a resiliência e tratamento de erros

src/api/direto/direto.controller.ts, src/api/direto/direto.service.ts
- Remove guards de autenticação temporariamente para testes
- Verifica existência de solicitação antes de criar cliente
=> 🐛 fix: Corrige autenticação na criação de cliente Direto

prisma/schema.prisma, src/api/user/user.service.ts, src/prisma/prisma.service.ts
- Corrige a ordem dos campos ,  e  no model  do schema Prisma
- Remove o decorator  do método  em
- Modifica a lógica para acessar métodos do Prisma para tratamento de erros e tipagem correta
=> ♻️ refactor: Ajusta tipagem e tratamento de erros no Prisma

src/prisma/prisma.service.ts
- Permite chamadas com callback para decorator DatabaseResilient
- Implementa lógica de retry para o callback
- Garante compatibilidade com chamadas existentes (clientType, methodPath, ...args)
=> ✨ feat: Adiciona sobrecarga ao executeWithRetry

src/api/direto/direto.service.ts
- Inverte a condição  para  na verificação do andamento.
=> 🐛 fix: Inverte condição para verificar andamento

src/api/get-infos/get-infos.service.ts
- Removida a consulta e o retorno de dados financeiros desnecessários da API .
=> ♻️ refactor: Remove dados financeiros do retorno

src/api/direto/direto.controller.ts, src/api/direto/direto.service.ts, src/api/direto/dto/generate-cnad.dto.ts, src/api/direto/dto/parse-cnab.dto.ts
- Adiciona DTOs GenerateCnabDto e ParseCnabDto para validação dos dados
- Refatora serviço Direto para utilizar registro CNAB em vez de token criptografado
- Implementa método processar para unificar geração e interpretação
- Remove validação de AuthGuard da rota /create/link
=> ✨ feat: Implementa geração e interpretação de registro CNAB

src/api/direto/direto.service.ts
- Ajusta a query para buscar solicitações corretamente por CPF e andamento
- Garante que a busca inclua casos onde o andamento é nulo
=> 🐛 fix: Corrige busca de solicitação no Direto

src/api/solicitacao/solicitacao.service.ts, src/sequelize/providers/fcweb.ts
- Ajusta filtros de busca por hierarquia de usuário
- Corrige tipagem de retorno da busca no FCWeb
- Inclui dados do FCWeb no update da solicitação
=> 🐛 fix: Corrige filtros e busca de dados do FCWeb

src/api/direto/direto.controller.ts, src/api/direto/direto.service.ts
- Adiciona rota  no controller
- Implementa função  no service para buscar solicitações com status de pagamento pendente
=> ✨ feat: Adiciona endpoint para verificar pagamento por CPF

ecosystem.config.json
- Cria arquivo  para gerenciamento da aplicação com PM2.
=> 🔨 chore: Adiciona arquivo de configuração do PM2

src/api/solicitacao/solicitacao.service.ts
- Corrige a lógica de filtros para a busca de solicitações, permitindo a busca por andamento
- Melhora a validação de permissões ao buscar uma solicitação por ID, retornando erro 404 adequado
- Trata corretamente a data zero do MySQL (0000-00-00) ao formatar datas
=> 🐛 fix: Corrige filtros e validações na solicitação

prisma/schema.prisma, src/api/construtora/construtora.controller.ts, src/api/construtora/construtora.service.ts, src/api/financeiro/financeiro.service.ts, src/api/intelesign/intelesign.controller.ts, src/api/user/user.service.ts
- Adiciona endpoint  no controller e service da construtora.
- Filtra construtoras por status .
- Inclui campos  e  nos responses das APIs.
=> ✨ feat: Adiciona endpoint para listar construtoras Intellisign

src/api/construtora/construtora.service.ts, src/api/financeiro/financeiro.service.ts, src/api/get-infos/get-infos.controller.ts, src/api/get-infos/get-infos.service.ts, src/api/user/user.service.ts
- Adiciona endpoint  em
- Adiciona método  em  para verificar a existência do email no banco
- Refatora  e  para usar
=> ✨ feat: Adiciona endpoint para verificar email

.vscode/settings.json, src/api/get-infos/get-infos.controller.ts, src/api/get-infos/get-infos.service.ts, src/api/intelesign/intelesign.controller.ts, src/api/intelesign/intelesign.service.ts
- Adiciona endpoint  para verificar a existência do email no banco
- Adiciona endpoint  para verificar a existência do email com  no banco
- Adiciona endpoint  para verificar a existência do CPF no banco
- Refatora a lógica de verificação de email no  para retornar um booleano
- Corrige um erro de log ao enviar informações para o intelesign
=> ✨ feat: Adiciona endpoint para verificar email e CPF

src/api/direto/direto.service.ts, src/main.ts
- Adiciona o servidor de produção na documentação do swagger
- Remove console.log desnecessário no service de direto
=> ✨ feat: Adiciona servidor de produção no swagger

src/api/intelesign/intelesign.service.ts
- Adiciona ordenação decrescente por data de criação na busca
- Adiciona log da data ao criar registro
=> 🐛 fix: Corrige ordenação e log na criação de registro

prisma/schema.prisma, src/api/intelesign/intelesign.service.ts, src/api/solicitacao/solicitacao.service.ts
- Corrige a lógica de atualização do status do envelope para considerar os status 'done' e 'completed' como concluídos.
- Adiciona a flag  ao model de Solicitação no Prisma Schema
- Remove logs desnecessários
=> 🐛 fix: Corrige status do intelesign e adiciona flag Gov

src/api/intelesign/intelesign.service.ts
- Garante que as chamadas para  sejam aguardadas corretamente
=> 🐛 fix: Corrige chamadas assíncronas em loop

src/api/intelesign/dto/sign.dto.ts, src/api/intelesign/intelesign.service.ts
- Garante padronização do nome para maiúsculo sem acentos
- Padroniza e-mail para minúsculo
- Melhora a busca do signatário por UUID para otimizar a performance
=> 🐛 fix: Corrige tratamento de dados do signatário
